### ISSUE TITLE
Kind Update to Template v4.

### ISSUE THREAD

**Issue by dark-1** [Magisk-Modules-Repo/xposed_23#3]
@topjohnwu ,     
      
Sir,      
      
Kindly Update all Xposed Modules to Template v4.     
Will be Highly Appreciated.     

Thanking You.

**Comment by terrorist96** [comment]
I'm sure he'll do it before he pushes a Magisk update which cuts off < v4  template modules. :eyes:

**Comment by dark-1** [comment]
DoNe!!!
