### ISSUE TITLE
kindly update sdk23 to v88.

### ISSUE THREAD

**Issue by dark-1** [Magisk-Modules-Repo/xposed_23#4]
@topjohnwu , respected sir,

Kindly update this SDK 23 for rovo89's v88,
Just like you did for SDK 21.

Thanking you. 👍

**Comment by topjohnwu** [comment]
Didn't you read my OP in XDA?

**Comment by dark-1** [comment]
Ho!! sorry,

> The SDK 22, 23 builds are not updated to v88.0 yet, still waiting for Samsung compatible builds to come out

Ether I Missed OR IT wasn't there the movement I saw the OP.

Sorry for the Trouble, My Apologies. 👍
